### ISSUE TITLE
RE: userspaceIO and the BBB/Seth

### ISSUE THREAD

**Issue by silver2row** [sgjava/userspaceio#1]
Hello,

I am trying to connect a LED via your idea and run some software, i.e. ledtest.py. The software was already typed up and I wanted to try it on my BBB (BeagleBone Black).

I tried to run:

    gpiodetect 

and...

    gpioinfo

...

from: https://github.com/brgl/libgpiod.

Now...I watched a YouTube.com video on this idea from the Embedded Linux Conference.

...

I do not know exactly how to retrieve my pin numbering once I choose a pin to work w/.

I thought I did and worked towards this goal. I may have made some miscalculations along the way, too.

...

    line 25 on gpiochip0

is where I am trying to connect to the BBB but where exactly is this location on the BeagleBone Black?

...

Seth

P.S. I am going to test more until I can configure the BBB to work w/ this updated form of character device. Please reply if you can find time. Thank you, sir.

**Comment by silver2row** [comment]
Hello Once More,

I just used:

    gpioget gpiochip0 24

I received a 0. I then applied this tool cmd:

    gpioget --active-low gpiochip0 24

...

This in turn placed my active state to low or 1. 

Seth

P.S. I just cannot find pin names outside of "NC" so far. I will keep testing.

**Comment by sgjava** [comment]
http://beagleboard.org/support/bone101 gives you the pin mappings. You need to find all the gpio chips and remember they start at 0 for each chip. See https://github.com/sgjava/userspaceio#libgpiod where I illustrate how this is done for a NanoPi Duo. You will need to do the same thing for BBB.

**Comment by silver2row** [comment]
Hello Sir,

Thank you for this update. I found the NanoPi Duo info. that illustrated the pin for sysfs.

...

Seth

P.S. I am aware of the pin mappings of the BBB but not how they correlate w/ this idea for some reason. I will read more into it and keep trying.

**Comment by sgjava** [comment]
gpioinfo should give you the line name and number. Most are missing from NanoPi Duo, but it was enough to figure out enumeration of lines to gpio chips.

**Comment by silver2row** [comment]
Hello and Okay,

So, to get this correct...

All I do is type gpioinfo and I should receive my line name and number. Got it. When I type gpioinfo, I receive a bunch of lines on four different gpiochips, e.g. gpiochip0 - 3.

Seth

P.S. Each gpiochip has about 32 lines per chip. Some are saying used and others are stating not used/open.

**Comment by silver2row** [comment]
Hello Again Sir,

I can show you my print out in a gist if necessary. 

Seth

**Comment by sgjava** [comment]
Right, so once you have the gpio chip and line number you should be able to use the line names to figure out how things are mapped. You can send me gist output for gpioinfo and I should be able to give you an example.

**Comment by silver2row** [comment]
Hello and Thank You,

Here is the Gist of gpioinfo: https://gist.github.com/silver2row/deace30263609e227ba79ef4a9efca7a.

Seth

**Comment by sgjava** [comment]
OK, according to https://www.safaribooksonline.com/library/view/programming-the-beaglebone/9780071832120/appendixc.html it looks like GPIO_60 is P9_12 (pin 12 on P9 bus. So from libgpiod perspective you'd use gpiochip1 and line 28. Try hooking up an LED  to P9_12 and see if you can turn it on/off with gpioset.

**Comment by silver2row** [comment]
Hello,

Okay...I got the LED set up for managing the light, e.g. from the images section on your page on gitHub.com.

...

3.3v -> Resistor -> LED -> P9_12 (GPIO)

...


#gpioset: invalid offset<->value mapping: 28

    debian@beaglebone:~$ gpioset --mode=signal --background gpiochip1 28=1
    debian@beaglebone:~$ gpioset --mode=signal --background gpiochip1 28=0

gpiochip1 28=0 turned my LED on! You are a miracle worker! Thank you, sir.

Seth

P.S. I can set it by gpioset gpiochip1 28=1 and 28=0 for off, too.

**Comment by silver2row** [comment]
Sir,

Now for this offset business:

Since I am incorrect about this offset idea, I may need to know what you understood about this idea (if this is okay).

I read over the NanoPi Duo info. you have listed on your main page of userspaceio.

So, GPIO_60 is P9_12. Okay, I am w/ you so far. But...

Do I need to multiply the entire amount of pins and take, since I have 128 pins, 1 (for the gpiochip) and the 28 (for the pin number)? 

I know this sounds odd but I have not been able to configure my understanding any other way.

Seth

**Comment by sgjava** [comment]
You are lucky the NanoPi Duo has limited line names to figure things out from. You will see a pattern like I showed for the NanoPi Duo for physical pin to line mapping.

**Comment by silver2row** [comment]
Thank you sir.

Seth
