### ISSUE TITLE
Unable to open gpiochip0

### ISSUE THREAD

**Issue by mcoromac** [sgjava/userspaceio#2]
Hello, I'm trying to use the Java binding for libgpiod. 
I'm running my jar file using jamvm on an armv7 target. I already added the necessary jar files and have libgppiod installed. 
If I try to open gpiochip0 using the line: 
`final gpiod_chip chip = lib.gpiod_chip_open_by_number(chipNum);`
I get a Segmentation Fault. 
I enabled the jna debugger and this is the output:
```
Trying (via loadLibrary) jnidispatch
Looking in classpath from java.lang.ClassLoader$1{urls=[file:/mnt/usb/busses_project.jar], parent=null} for /com/sun/jna/linux-arm/libjnidispatch.so
Found library resource at jar:file:/mnt/usb/busses_project.jar!/com/sun/jna/linux-arm/libjnidispatch.so
Trying /tmp/jna-3506402/jna223b8.tmp
Found jnidispatch at /tmp/jna-3506402/jna223b8.tmp
Looking for library 'gpiod'
Adding paths from jna.library.path: null
Trying libgpiod.so
Found library 'gpiod' at libgpiod.so
Looking for library 'gpiod'
Adding paths from jna.library.path: null
Trying libgpiod.so
Found library 'gpiod' at libgpiod.so
```
This output makes me think that there is nothing wrong with loading the library. 
And if I try with any of these:
```
final gpiod_chip chip = lib.gpiod_chip_open_by_label("/sys/class/gpio/gpiochip0");
final gpiod_chip chip = lib.gpiod_chip_open("/sys/class/gpio/gpiochip0")
final gpiod_chip chip = lib.gpiod_chip_open_by_label("gpiochip0");
```

My chip object keeps at null. 
I can run the libgpiod tools and I also can export and use the pins manually. 

Any ideas on how to debug this? 

Thank you!

**Comment by sgjava** [comment]
Did you see and problems in the install logs? I saw and issue with ARM64 I'm working on now. Check the *.log files for errors.

**Comment by sgjava** [comment]
Try the following:
- rm -rf userspaceio/ c-periphery/ libgpiod/
- git clone --depth 1 https://github.com/sgjava/userspaceio.git
- cd ~/userspaceio/jnaerator
- sudo ./install-java.sh (this will force java artifacts to install)
- cd ../
- ./install.sh

All the Java libs build now.

**Comment by sgjava** [comment]
I validated Java scripts are working. If you still have an issue open a new issue or comment here and I'll look at it.

**Comment by mcoromac** [comment]
The new jna-4.5.2.jar made it work! Thanks.

**Comment by sgjava** [comment]
Cool, thanks for reporting back.
