### ISSUE TITLE
Can't find Spi class.

### ISSUE THREAD

**Issue by mcoromac** [sgjava/userspaceio#3]
Hello,
I'm trying to use c-periphery java binding. However I can't find the class anywhere. When I try to import like this:
import com.codeferm.Spi;
It says codeferm is not resolved. 
I checked the preocompiled libperiphery.java but is not there. Should it? 
The example I'm using is called SpiLoopback.java
Inside java-bindings.log the first thing that looks like an error is this: 
```
com.ochafik.lang.jnaerator.JNAerator$CommandLineException: Error parsing arguments :
-library peripheryi2c -mode Directory -runtime JNA -preferJavac -beanStructs -noLibBundle /usr/local/lib/libperipheryi2c.so /usr/include/arm-linux-gnueabihf/asm/types.h /usr/include/linux/types.h /usr/include/linux/i2c.h ../../../c-periphery/src/i2c.h : java.io.FileNotFoundException: /usr/include/arm-linux-gnueabihf/asm/types.h
	at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:160)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:791)
	at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:203)
Caused by: java.io.FileNotFoundException: /usr/include/arm-linux-gnueabihf/asm/types.h
	at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$OptionDef$ArgDef.convertArg(JNAeratorCommandLineArgs.java:469)
	at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:150)
	... 2 more
#
# ERROR: JNAeration failed !
```

Am I doing something wrong? Thanks!

**Comment by sgjava** [comment]
Try **find /usr/include -name types.h** and reply with output.

**Comment by mcoromac** [comment]
/usr/include/newlib/machine/types.h
/usr/include/newlib/sys/types.h
/usr/include/newlib/c++/6.3.1/parallel/types.h
/usr/include/asm-generic/types.h
/usr/include/rpc/types.h
/usr/include/x86_64-linux-gnu/asm/types.h
/usr/include/x86_64-linux-gnu/bits/types.h
/usr/include/x86_64-linux-gnu/sys/types.h
/usr/include/linux/types.h
/usr/include/linux/iio/types.h
/usr/include/linux/sched/types.h
/usr/include/c++/7/parallel/types.h
/usr/include/c++/5/parallel/types.h

Where can I specify the directory from which it goes looking for types.h?

**Comment by sgjava** [comment]
This looks like you are building on an x86_64 machine? /usr/include/arm-linux-gnueabihf/asm/types.h should be where it is located if kernel headers were installed on ARM. I've never tried x86, but it should work. I build OpenCV on both ARM/x86, but there are not many x86 platforms with GPIO, etc.

**Comment by mcoromac** [comment]
Yes I am building on a x86_64 machine but my target is an arm7v. I'm using buildroot for my target and I don't have a jdk installed. I just have a Java Virtual Machine, buildroot does have c-periphery package so I figured I could adapt your jar library into my own needs. I thought I could just use the libperiphery.jar library.

If I'm not mistaken I just need to correctly point the script into my buildroot directory so jnaerator can create the library. I already fixed the types.h error with that. However now shows this: 
```
Parsing native headers...
/usr/include/asm-generic/int-ll64.h:10:0: error: File not found: asm/bitsperlong.h in . /usr/include /usr/local/include /usr/include/c++/7.3.0 /usr/include/c++/7.3.0/tr1
```
If this goes out of your scope I'm sorry, I'll close the issue if that's what you want.

**Comment by sgjava** [comment]
Actually the pre built jars are for ARMv8 since JNAerator will shart itself and die on that platform. You can use the pre built jars though on any platform assuming the shared objects are installed. For instance I can compile demos:

- cd ~/userspaceio/c-periphery
- javac -cp ../../jnaerator/jna-4.5.2.jar:../../jnaerator/jnaerator-runtime.jar:libperiphery.jar src/com/codeferm/*.java src/com/codeferm/demo/*.java

Then to run the SPI demo with loop back wire:

java -Djna.nosys=true -Djava.library.path=/usr/local/lib -cp ../../jnaerator/jna-4.5.2.jar:../../jnaerator/jnaerator-runtime.jar:libperiphery.jar:demo.jar com.codeferm.demo.SpiLoopback /dev/spidev0.0 500000﻿

In any event the scripts are designed to build on the targets, so you may run into issues with cross compiling since I never tested that. You can look at the individual scripts to see what they are doing.

**Comment by mcoromac** [comment]
I just did that! I mistakenly thought 
import com.codeferm.Spi;
was another library. So I just added the class into my main program. 

I noted in your script that you save the objects as shared libraries since c-periphery is built as static by default. I just needed to find a dynamic linking for my arch and create the shared libraries. I just did that. I'm going to test it now and let you know!

**Comment by sgjava** [comment]
Cool, yea everything is a SO to reduce the amount of duplicate code.

**Comment by mcoromac** [comment]
It works! Thanks for your support!

**Comment by sgjava** [comment]
Great, please look at the demo code since that will give you the nuances of using the generated libs. It's not as simple as Python or C.

**Comment by mcoromac** [comment]
I will! We choose Java because it's better for our application.

**Comment by sgjava** [comment]
I still need to look at Java 11 since that's LTS now. I'm just worried about JNAerator working under Java 11. I can still build jars under Java 8 and use them in Java 11.

**Comment by mcoromac** [comment]
Oh, I had some troubles cross compiling classpath0.99 using java 11. I had to stick to java 8. 
My virtual machine (jamvm) is mostly java 5 compilant and I'm using gnuclasspath as my class library because is lightweight compared to openjdk :/ pros and cons.
