### ISSUE TITLE
ModuleNotFoundError: No module named 'gpiod'

### ISSUE THREAD

**Issue by iomari** [sgjava/userspaceio#6]
Greetings,
when running the python examples, I get "ModuleNotFoundError: No module named 'gpiod'".

How do I install the gpiod library? I installed userspaceio using the top level install.sh  with no errors.
I using this on a beaglebone black running ubuntu 18.

thanks

**Comment by sgjava** [comment]
`find /usr/local/lib -name gpiod.so
/usr/local/lib/python3.6/site-packages/gpiod.so`

`export PYTHONPATH=/usr/local/lib/python3.6/site-packages`

See https://github.com/sgjava/userspaceio#python-bindings
