### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by MGlolenstine** [sgjava/userspaceio#7]
I found [this thread](https://libraries.io/github/sgjava/libgpiod-extra), but there's no repository on your account called `libgpiod-extra`.
Could you fix the link please!

**Comment by sgjava** [comment]
I never created this page. It looks like a snapshot from 2018 and that project was deleted.

**Comment by MGlolenstine** [comment]
My bad! I thought it was about people posting their libraries, but it's apparently autogenerated pages of promising GitHub repos!

**Comment by sgjava** [comment]
No worries, but I guess they do not check if the repo still exists :)

**Comment by MGlolenstine** [comment]
I requested the refresh, so now it shows that the repo has been removed.
https://libraries.io/github/sgjava/libgpiod-extra

**Comment by sgjava** [comment]
So much for automation :) You'd think they would scrape the site for updates.

**Comment by MGlolenstine** [comment]
Well, it might be against Github's TOS or something... Apparently anyone can contribute to that website, even if the repo is not yours... I guess that's how it was added...
